apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:peawdev/k8s-app-of-app-argocd.git
    targetRevision: main
    path: app
    directory:
      recurse: true
  destination:
    server: gke_k8s-ms-dev_asia-southeast1_cluster-demo-2
    namespace: default
  syncPolicy:
    automated:
      prune: true