apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-prod-config-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:peawdev/k8s-calculator-config-prod.git
    targetRevision: main
    path: ./
  destination:
    server: https://34.142.138.192
    namespace: peaw-dev
  syncPolicy:
    automated:
      prune: true