apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:peawdev/k8s-calculator-prod.git
    targetRevision: main
    path: ./
    # directory:
    #   recurse: true
    helm:
      releaseName: calculator-prod
      valueFiles:
        - values.yaml
  destination:
    server: gke_k8s-ms-dev_asia-southeast1_cluster-demo
    namespace: peaw-dev
  syncPolicy:
    automated:
      prune: true